import { Document, Page, View, Text } from "@react-pdf/renderer";
import {
  BRAND,
  REPORT_LABELS,
  type ReportKind,
} from "../branding";
import { createStyles } from "./styles";
import { EnvironmentalSection } from "./sections/EnvironmentalSection";
import { SocialSection } from "./sections/SocialSection";
import { GovernanceSection } from "./sections/GovernanceSection";
import { ESGSummarySection } from "./sections/ESGSummarySection";

function ReportFooter({ kind }: { kind: ReportKind }) {
  const s = createStyles(kind);
  return (
    <View style={s.footer} fixed>
      <Text>{BRAND.confidentiality}</Text>
      <Text>Generated by {BRAND.platformFull}</Text>
    </View>
  );
}

export function ReportDocument({ kind }: { kind: ReportKind }) {
  const s = createStyles(kind);
  const accent = REPORT_LABELS[kind];

  return (
    <Document
      title={REPORT_LABELS[kind]}
      author={BRAND.organization}
      subject={REPORT_LABELS[kind]}
    >
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View style={s.headerLeft}>
            <Text style={s.title}>{REPORT_LABELS[kind]}</Text>
            <Text style={s.subtitle}>{BRAND.platformFull} — {BRAND.organization}</Text>
          </View>
          <View style={s.headerRight}>
            <Text style={s.brandName}>{BRAND.platform}</Text>
            <Text style={s.confidentiality}>{BRAND.confidentiality}</Text>
          </View>
        </View>

        {kind === "environmental" && <EnvironmentalSection kind={kind} />}
        {kind === "social" && <SocialSection kind={kind} />}
        {kind === "governance" && <GovernanceSection kind={kind} />}
        {kind === "esg" && <ESGSummarySection kind={kind} />}
        {kind === "custom" && <ESGSummarySection kind={kind} />}

        <View style={s.disclaimer}>
          <Text>
            This report is generated automatically by {BRAND.platformFull}. Data is based on
            employee-submitted records and may be subject to verification. For any discrepancies,
            please contact the ESG administration team. {BRAND.website}
          </Text>
        </View>

        <ReportFooter kind={kind} />
      </Page>
    </Document>
  );
}
